# Nearest Restaurants in Madrid

In [3]:
# Dependencies
import pandas as pd
import numpy as np
import requests
import json

# Import the API key
from config import geoapify_key

In [4]:
# Load the restaurant ethnicities into a DataFrame
types_df = pd.read_csv("../Resources/ethnicities.csv")

# Display sample data
types_df.head()

  ethnicity
0   italian
1   chinese
2   mexican
3  japanese
4  american

In [5]:
# Set up additional columns to hold information
types_df["name"] = ""
types_df["address"] = ""
types_df["distance"] = ""

# Display sample data
types_df.head()

  ethnicity name address distance
0   italian
1   chinese
2   mexican
3  japanese
4  american

Find the closest restaurant of each type to the Plaza Mayor in Madrid, Spain

* Latitude: 40.415392

* Longitude: -3.7073743182788528

In [22]:
# Target city
target_city = "Kansas City, MO"

# Build the endpoint URL
target_url = f"https://api.geoapify.com/v1/geocode/search?text={target_city}&format=json&apiKey={geoapify_key}"
geo_data = requests.get(target_url).json()
latitude = geo_data["results"][0]["lat"]
longitude = geo_data["results"][0]["lon"]
print(latitude, longitude)

39.100105 -94.5781416

In [41]:
# Set the geographical coordinates
#latitude = 40.415392
#longitude = -3.7073743182788528

# Set the parameters for the type of search
limit = 20
radius = 5000
filters = f"circle:{longitude},{latitude},{radius}"
bias = f"proximity:{longitude},{latitude}"

# set up a parameters dictionary
params = {
    "filter":filters,
    "limit":limit,
    "bias":bias,
    "apiKey":geoapify_key    
}

# Set base URL
base_url = "https://api.geoapify.com/v2/places"

In [42]:
import time

In [43]:
# Print a message to follow up the restaurant search
print("Starting restaurant search")

# Iterate through the types_df DataFrame
for index, row in types_df.iterrows():
    time.sleep(1)
    # Get the ethnicity type from the current DataFrame's row
    ethnicity =row['ethnicity']
    # Add the current ethnicity type to the parameters
    params["categories"]=f"catering.restaurant.{ethnicity}"
   
    # Make an API request using the params dictionary
    restaurant = requests.get(base_url,params=params)
    #print(restaurant.url)
    #https://api.geoapify.com/v2/places?filter=circle%3A-95.677556%2C39.049011%2C1000&limit=20&bias=proximity%3A-95.677556%2C39.049011&apiKey=7a82d4cd259a431aa407abcfbdefb62d&categories=catering.restaurant.italian
    # Convert the API response to JSON format
    restaurant_json =  restaurant.json()
    
    # Grab the first restaurant from the results and store the details in the DataFrame
    try:
        name = restaurant_json['features'][0]['properties']['name']
        address = restaurant_json['features'][0]['properties']['address_line2']
        distance =restaurant_json['features'][0]['properties']['distance'] 
        print(index,name,address,distance)
        types_df.loc[index, "name"] = name
        types_df.loc[index, "address"] = address
        types_df.loc[index, "distance"] = distance
    except (KeyError, IndexError):
        # If no restaurant is found, set the restaurant name as "No restaurant found".
        print("error")
        # Set the distance column value to np.nan to allow sorting values
        types_df.loc[index, "name"] = "No restaurant found"
        types_df.loc[index, "distance"] = np.nan
        
        
    # Log the search results
    print(f"nearest {types_df.loc[index, 'ethnicity']} restaurant: {types_df.loc[index, 'name']}")

# Display sample data
types_df

Starting restaurant search
4 Yard House 1300 Main Street, Downtown Kansas City, MO 64105, United States of America 497
nearest american restaurant: Yard House
0 Anthony's 701 Grand Boulevard, Downtown Kansas City, MO 64106, United States of America 584
nearest italian restaurant: Anthony's
33 Blue Nile Cafe 20 East 5th Street, Downtown Kansas City, MO 64106, United States of America 1010
nearest ethiopian restaurant: Blue Nile Cafe
5 Tikka House 411 Main Street, Downtown Kansas City, MO 64105, United States of America 1067
nearest indian restaurant: Tikka House
12 Vietnam Cafe 520-522 Campbell Street, Kansas City, MO 64106, United States of America 1108
nearest vietnamese restaurant: Vietnam Cafe
9 Baramee Thai Bistro 1810 Baltimore Avenue, Downtown Kansas City, MO 64108, United States of America 1128
nearest thai restaurant: Baramee Thai Bistro
2 Los Tules 1656 Broadway Boulevard, Downtown Kansas City, MO 64108, United States of America 1193
nearest mexican restaurant: Los Tules
8 Affäre 1911 Main Street, Downtown Kansas City, MO 64108, United States of America 1211
nearest german restaurant: Affäre
1 Green River Chinese & Vietnamese 2120 East 12th Street, Kansas City, MO 64127, United States of America 1836
nearest chinese restaurant: Green River Chinese & Vietnamese
error
nearest japanese restaurant: No restaurant found
error
nearest asian restaurant: No restaurant found
error
nearest french restaurant: No restaurant found
error
nearest greek restaurant: No restaurant found
error
nearest tex-mex restaurant: No restaurant found
error
nearest turkish restaurant: No restaurant found
error
nearest korean restaurant: No restaurant found
15 La Bodega 703 Southwest Boulevard, Kansas City, MO 64108, United States of America 3514
nearest spanish restaurant: La Bodega
error
nearest lebanese restaurant: No restaurant found
error
nearest indonesian restaurant: No restaurant found
error
nearest portuguese restaurant: No restaurant found
error
nearest arab restaurant: No restaurant found
error
nearest russian restaurant: No restaurant found
error
nearest filipino restaurant: No restaurant found
error
nearest african restaurant: No restaurant found
error
nearest malaysian restaurant: No restaurant found
error
nearest caribbean restaurant: No restaurant found
error
nearest peruvian restaurant: No restaurant found
error
nearest bavarian restaurant: No restaurant found
error
nearest brazilian restaurant: No restaurant found
error
nearest persian restaurant: No restaurant found
error
nearest argentinian restaurant: No restaurant found
error
nearest oriental restaurant: No restaurant found
error
nearest balkan restaurant: No restaurant found
error
nearest moroccan restaurant: No restaurant found
error
nearest taiwanese restaurant: No restaurant found
error
nearest latin_american restaurant: No restaurant found
36 Hawaiian Bros 101 Armour Road, North Kansas City, MO 64116, United States of America 4591
nearest hawaiian restaurant: Hawaiian Bros
error
nearest irish restaurant: No restaurant found
error
nearest austrian restaurant: No restaurant found
error
nearest croatian restaurant: No restaurant found
error
nearest danish restaurant: No restaurant found
error
nearest bolivian restaurant: No restaurant found
error
nearest hungarian restaurant: No restaurant found
error
nearest european restaurant: No restaurant found
error
nearest jamaican restaurant: No restaurant found
error
nearest cuban restaurant: No restaurant found
error
nearest uzbek restaurant: No restaurant found
error
nearest nepalese restaurant: No restaurant found
error
nearest czech restaurant: No restaurant found
error
nearest syrian restaurant: No restaurant found
error
nearest afghan restaurant: No restaurant found
error
nearest malay restaurant: No restaurant found
error
nearest belgian restaurant: No restaurant found
error
nearest ukrainian restaurant: No restaurant found
error
nearest swedish restaurant: No restaurant found
error
nearest pakistani restaurant: No restaurant found

,ethnicity,name,address,distance
4,american,Yard House,"1300 Main Street, Downtown Kansas City, MO 641...",497
0,italian,Anthony's,"701 Grand Boulevard, Downtown Kansas City, MO ...",584
33,ethiopian,Blue Nile Cafe,"20 East 5th Street, Downtown Kansas City, MO 6...",1010
5,indian,Tikka House,"411 Main Street, Downtown Kansas City, MO 6410...",1067
12,vietnamese,Vietnam Cafe,"520-522 Campbell Street, Kansas City, MO 64106...",1108
9,thai,Baramee Thai Bistro,"1810 Baltimore Avenue, Downtown Kansas City, M...",1128
2,mexican,Los Tules,"1656 Broadway Boulevard, Downtown Kansas City,...",1193
8,german,Affäre,"1911 Main Street, Downtown Kansas City, MO 641...",1211
1,chinese,Green River Chinese & Vietnamese,"2120 East 12th Street, Kansas City, MO 64127, ...",1836
3,japanese,No restaurant found,,NaN
6,asian,No restaurant found,,NaN
7,french,No restaurant found,,NaN
10,greek,No restaurant found,,NaN
11,tex-mex,No restaurant found,,NaN
13,turkish,No restaurant found,,NaN
14,korean,No restaurant found,,NaN
15,spanish,La Bodega,"703 Southwest Boulevard, Kansas City, MO 64108...",3514
16,lebanese,No restaurant found,,NaN
17,indonesian,No restaurant found,,NaN
18,portuguese,No restaurant found,,NaN
19,arab,No restaurant found,,NaN
20,russian,No restaurant found,,NaN
21,filipino,No restaurant found,,NaN
22,african,No restaurant found,,NaN
23,malaysian,No restaurant found,,NaN
24,caribbean,No restaurant found,,NaN
25,peruvian,No restaurant found,,NaN
26,bavarian,No restaurant found,,NaN
27,brazilian,No restaurant found,,NaN
28,persian,No restaurant found,,NaN
29,argentinian,No restaurant found,,NaN
30,oriental,No restaurant found,,NaN
31,balkan,No restaurant found,,NaN
32,moroccan,No restaurant found,,NaN
34,taiwanese,No restaurant found,,NaN
35,latin_american,No restaurant found,,NaN
36,hawaiian,Hawaiian Bros,"101 Armour Road, North Kansas City, MO 64116, ...",4591
37,irish,No restaurant found,,NaN
38,austrian,No restaurant found,,NaN
39,croatian,No restaurant found,,NaN
40,danish,No restaurant found,,NaN
41,bolivian,No restaurant found,,NaN
42,hungarian,No restaurant found,,NaN
43,european,No restaurant found,,NaN
44,jamaican,No restaurant found,,NaN
45,cuban,No restaurant found,,NaN
46,uzbek,No restaurant found,,NaN
47,nepalese,No restaurant found,,NaN
48,czech,No restaurant found,,NaN
49,syrian,No restaurant found,,NaN
50,afghan,No restaurant found,,NaN
51,malay,No restaurant found,,NaN
52,belgian,No restaurant found,,NaN
53,ukrainian,No restaurant found,,NaN
54,swedish,No restaurant found,,NaN
55,pakistani,No restaurant found,,NaN

In [45]:
# Sort restuls by distance
types_df = types_df.sort_values(by=["distance"])

# Display the top 10 nearest restaurants
types_df.head(15)

,ethnicity,name,address,distance
4,american,Yard House,"1300 Main Street, Downtown Kansas City, MO 641...",497
0,italian,Anthony's,"701 Grand Boulevard, Downtown Kansas City, MO ...",584
33,ethiopian,Blue Nile Cafe,"20 East 5th Street, Downtown Kansas City, MO 6...",1010
5,indian,Tikka House,"411 Main Street, Downtown Kansas City, MO 6410...",1067
12,vietnamese,Vietnam Cafe,"520-522 Campbell Street, Kansas City, MO 64106...",1108
9,thai,Baramee Thai Bistro,"1810 Baltimore Avenue, Downtown Kansas City, M...",1128
2,mexican,Los Tules,"1656 Broadway Boulevard, Downtown Kansas City,...",1193
8,german,Affäre,"1911 Main Street, Downtown Kansas City, MO 641...",1211
1,chinese,Green River Chinese & Vietnamese,"2120 East 12th Street, Kansas City, MO 64127, ...",1836
15,spanish,La Bodega,"703 Southwest Boulevard, Kansas City, MO 64108...",3514
36,hawaiian,Hawaiian Bros,"101 Armour Road, North Kansas City, MO 64116, ...",4591
3,japanese,No restaurant found,,NaN
6,asian,No restaurant found,,NaN
7,french,No restaurant found,,NaN
10,greek,No restaurant found,,NaN

In [52]:

for index, row in types_df.iterrows():
    print(index,row['name'])
    row['address'] ='hoobastank'

4 Yard House
0 Anthony's
33 Blue Nile Cafe
5 Tikka House
12 Vietnam Cafe
9 Baramee Thai Bistro
2 Los Tules
8 Affäre
1 Green River Chinese & Vietnamese
15 La Bodega
36 Hawaiian Bros
3 No restaurant found
6 No restaurant found
7 No restaurant found
10 No restaurant found
11 No restaurant found
13 No restaurant found
14 No restaurant found
16 No restaurant found
17 No restaurant found
18 No restaurant found
19 No restaurant found
20 No restaurant found
21 No restaurant found
22 No restaurant found
23 No restaurant found
24 No restaurant found
25 No restaurant found
26 No restaurant found
27 No restaurant found
28 No restaurant found
29 No restaurant found
30 No restaurant found
31 No restaurant found
32 No restaurant found
34 No restaurant found
35 No restaurant found
37 No restaurant found
38 No restaurant found
39 No restaurant found
40 No restaurant found
41 No restaurant found
42 No restaurant found
43 No restaurant found
44 No restaurant found
45 No restaurant found
46 No restaurant found
47 No restaurant found
48 No restaurant found
49 No restaurant found
50 No restaurant found
51 No restaurant found
52 No restaurant found
53 No restaurant found
54 No restaurant found
55 No restaurant found

In [58]:
types_df = types_df.rename(columns={'address': "AddressHoobastank"})
types_df

,ethnicity,name,AddressHoobastank,distance
4,american,Yard House,hoobastank,497
0,italian,Anthony's,hoobastank,584
33,ethiopian,Blue Nile Cafe,hoobastank,1010
5,indian,Tikka House,hoobastank,1067
12,vietnamese,Vietnam Cafe,hoobastank,1108
9,thai,Baramee Thai Bistro,hoobastank,1128
2,mexican,Los Tules,hoobastank,1193
8,german,Affäre,hoobastank,1211
1,chinese,Green River Chinese & Vietnamese,hoobastank,1836
15,spanish,La Bodega,hoobastank,3514
36,hawaiian,Hawaiian Bros,hoobastank,4591
3,japanese,No restaurant found,hoobastank,NaN
6,asian,No restaurant found,hoobastank,NaN
7,french,No restaurant found,hoobastank,NaN
10,greek,No restaurant found,hoobastank,NaN
11,tex-mex,No restaurant found,hoobastank,NaN
13,turkish,No restaurant found,hoobastank,NaN
14,korean,No restaurant found,hoobastank,NaN
16,lebanese,No restaurant found,hoobastank,NaN
17,indonesian,No restaurant found,hoobastank,NaN
18,portuguese,No restaurant found,hoobastank,NaN
19,arab,No restaurant found,hoobastank,NaN
20,russian,No restaurant found,hoobastank,NaN
21,filipino,No restaurant found,hoobastank,NaN
22,african,No restaurant found,hoobastank,NaN
23,malaysian,No restaurant found,hoobastank,NaN
24,caribbean,No restaurant found,hoobastank,NaN
25,peruvian,No restaurant found,hoobastank,NaN
26,bavarian,No restaurant found,hoobastank,NaN
27,brazilian,No restaurant found,hoobastank,NaN
28,persian,No restaurant found,hoobastank,NaN
29,argentinian,No restaurant found,hoobastank,NaN
30,oriental,No restaurant found,hoobastank,NaN
31,balkan,No restaurant found,hoobastank,NaN
32,moroccan,No restaurant found,hoobastank,NaN
34,taiwanese,No restaurant found,hoobastank,NaN
35,latin_american,No restaurant found,hoobastank,NaN
37,irish,No restaurant found,hoobastank,NaN
38,austrian,No restaurant found,hoobastank,NaN
39,croatian,No restaurant found,hoobastank,NaN
40,danish,No restaurant found,hoobastank,NaN
41,bolivian,No restaurant found,hoobastank,NaN
42,hungarian,No restaurant found,hoobastank,NaN
43,european,No restaurant found,hoobastank,NaN
44,jamaican,No restaurant found,hoobastank,NaN
45,cuban,No restaurant found,hoobastank,NaN
46,uzbek,No restaurant found,hoobastank,NaN
47,nepalese,No restaurant found,hoobastank,NaN
48,czech,No restaurant found,hoobastank,NaN
49,syrian,No restaurant found,hoobastank,NaN
50,afghan,No restaurant found,hoobastank,NaN
51,malay,No restaurant found,hoobastank,NaN
52,belgian,No restaurant found,hoobastank,NaN
53,ukrainian,No restaurant found,hoobastank,NaN
54,swedish,No restaurant found,hoobastank,NaN
55,pakistani,No restaurant found,hoobastank,NaN

In [59]:
types_df

,ethnicity,name,AddressHoobastank,distance
4,american,Yard House,hoobastank,497
0,italian,Anthony's,hoobastank,584
33,ethiopian,Blue Nile Cafe,hoobastank,1010
5,indian,Tikka House,hoobastank,1067
12,vietnamese,Vietnam Cafe,hoobastank,1108
9,thai,Baramee Thai Bistro,hoobastank,1128
2,mexican,Los Tules,hoobastank,1193
8,german,Affäre,hoobastank,1211
1,chinese,Green River Chinese & Vietnamese,hoobastank,1836
15,spanish,La Bodega,hoobastank,3514
36,hawaiian,Hawaiian Bros,hoobastank,4591
3,japanese,No restaurant found,hoobastank,NaN
6,asian,No restaurant found,hoobastank,NaN
7,french,No restaurant found,hoobastank,NaN
10,greek,No restaurant found,hoobastank,NaN
11,tex-mex,No restaurant found,hoobastank,NaN
13,turkish,No restaurant found,hoobastank,NaN
14,korean,No restaurant found,hoobastank,NaN
16,lebanese,No restaurant found,hoobastank,NaN
17,indonesian,No restaurant found,hoobastank,NaN
18,portuguese,No restaurant found,hoobastank,NaN
19,arab,No restaurant found,hoobastank,NaN
20,russian,No restaurant found,hoobastank,NaN
21,filipino,No restaurant found,hoobastank,NaN
22,african,No restaurant found,hoobastank,NaN
23,malaysian,No restaurant found,hoobastank,NaN
24,caribbean,No restaurant found,hoobastank,NaN
25,peruvian,No restaurant found,hoobastank,NaN
26,bavarian,No restaurant found,hoobastank,NaN
27,brazilian,No restaurant found,hoobastank,NaN
28,persian,No restaurant found,hoobastank,NaN
29,argentinian,No restaurant found,hoobastank,NaN
30,oriental,No restaurant found,hoobastank,NaN
31,balkan,No restaurant found,hoobastank,NaN
32,moroccan,No restaurant found,hoobastank,NaN
34,taiwanese,No restaurant found,hoobastank,NaN
35,latin_american,No restaurant found,hoobastank,NaN
37,irish,No restaurant found,hoobastank,NaN
38,austrian,No restaurant found,hoobastank,NaN
39,croatian,No restaurant found,hoobastank,NaN
40,danish,No restaurant found,hoobastank,NaN
41,bolivian,No restaurant found,hoobastank,NaN
42,hungarian,No restaurant found,hoobastank,NaN
43,european,No restaurant found,hoobastank,NaN
44,jamaican,No restaurant found,hoobastank,NaN
45,cuban,No restaurant found,hoobastank,NaN
46,uzbek,No restaurant found,hoobastank,NaN
47,nepalese,No restaurant found,hoobastank,NaN
48,czech,No restaurant found,hoobastank,NaN
49,syrian,No restaurant found,hoobastank,NaN
50,afghan,No restaurant found,hoobastank,NaN
51,malay,No restaurant found,hoobastank,NaN
52,belgian,No restaurant found,hoobastank,NaN
53,ukrainian,No restaurant found,hoobastank,NaN
54,swedish,No restaurant found,hoobastank,NaN
55,pakistani,No restaurant found,hoobastank,NaN